targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          scalar_mapping:
            - graphql_type: JSON
              dart_type: Map<String, dynamic>
            - graphql_type : DateTime
              dart_type : DateTime
          schema_mapping:
            - schema: schema.graphql
              queries_glob: lib/graphql/*.graphql
              output: lib/gen/graphql/graphql_api.dart
              resolve_type_field: __typename
              naming_scheme: pathedWithFields
